CREATE TABLE "EXPERIMENT" (
	"EXPERIMENT_ID" int NOT NULL ,
	"OWNER_ID" int NOT NULL ,
	"SUBJECT_PERSON_ID" int NOT NULL ,
	"SCENARIO_ID" int NOT NULL ,
	"WEATHER_ID" int NOT NULL ,
	"RESEARCH_GROUP_ID" int NOT NULL ,
	"START_TIME" DATE,
	"END_TIME" DATE,
	"TEMPERATURE" SMALLINT,
	"WEATHERNOTE" varchar (255),
	"PRIVATE" int DEFAULT 0 NOT NULL ,
	"TITLE" varchar(100),
	"ORA_ROWSCN" BIGINT,
PRIMARY KEY ("EXPERIMENT_ID")
)
;

CREATE TABLE "PERSON" (
	"PERSON_ID" int NOT NULL ,
	"DEFAULT_GROUP_ID" int,
	"GIVENNAME" varchar (50),
	"SURNAME" varchar (50) NOT NULL ,
	"DATE_OF_BIRTH" DATE,
	"GENDER" CHAR (1) NOT NULL  CONSTRAINT "FILLED_GENDER" CHECK (GENDER = 'M' OR GENDER='F' ) ,
	"EMAIL" varchar (50),
	"PHONE_bigint" varchar (20),
	"NOTE" varchar (255),
	"USERNAME" varchar (50) UNIQUE ,
	"PASSWORD" varchar (50),
	"AUTHORITY" varchar (50),
	"CONFIRMED" int DEFAULT 0,
	"AUTHENTICATION" varchar (50),
	"REGISTRATION_DATE" DATE,
	"ORA_ROWSCN" BIGINT,
PRIMARY KEY ("PERSON_ID")
)
;

CREATE TABLE "COEXPERIMENTER_REL" (
	"PERSON_ID" int NOT NULL ,
	"EXPERIMENT_ID" int NOT NULL ,
PRIMARY KEY ("PERSON_ID","EXPERIMENT_ID")
)
;

CREATE TABLE "SCENARIO" (
	"SCENARIO_ID" int NOT NULL ,
	"OWNER_ID" int NOT NULL ,
	"RESEARCH_GROUP_ID" int NOT NULL ,
	"TITLE" varchar (40) CONSTRAINT "UNIQUE_SCENARIO_TITLE" UNIQUE ,
	"SCENARIO_LENGTH" INT,
	"SCENARIO_XML" clob,
	"DESCRIPTION" varchar (255),
	"PRIVATE" int DEFAULT 0 NOT NULL ,
	"SCENARIO_NAME" varchar (100) NOT NULL ,
	"MIMETYPE" varchar (30) NOT NULL ,
	"ORA_ROWSCN" BIGINT,
PRIMARY KEY ("SCENARIO_ID")
)
;

CREATE TABLE "HARDWARE" (
	"HARDWARE_ID" int NOT NULL ,
	"TITLE" varchar (50) NOT NULL  CONSTRAINT "UNIQUE_HARDWARE_TITLE" UNIQUE ,
	"TYPE" varchar (30) NOT NULL  CONSTRAINT "UNIQUE_HARDWARE_TYPE" UNIQUE ,
	"DESCRIPTION" varchar (30) CONSTRAINT "UNIQUE_HARDWARE_DESCRIPTION" UNIQUE ,
	"ORA_ROWSCN" BIGINT,
PRIMARY KEY ("HARDWARE_ID")
)
;

CREATE TABLE "HARDWARE_USAGE_REL" (
	"HARDWARE_ID" int NOT NULL ,
	"EXPERIMENT_ID" int NOT NULL ,
PRIMARY KEY ("HARDWARE_ID","EXPERIMENT_ID")
)
;

CREATE TABLE "DATA_FILE" (
	"DATA_FILE_ID" int NOT NULL ,
	"SAMPLING_RATE" FLOAT NOT NULL ,
	"FILE_CONTENT" BLOB,
	"EXPERIMENT_ID" int NOT NULL ,
	"MIMETYPE" varchar (40) NOT NULL ,
	"FILENAME" varchar (80) NOT NULL ,
	"FILE_LENGTH" BIGINT NOT NULL,
	"ORA_ROWSCN" BIGINT,
PRIMARY KEY ("DATA_FILE_ID")
)
;

CREATE TABLE "FILE_METADATA_PARAM_VAL" (
	"FILE_METADATA_PARAM_DEF_ID" int NOT NULL ,
	"DATA_FILE_ID" int NOT NULL ,
	"METADATA_VALUE" varchar(30) NOT NULL ,
PRIMARY KEY ("FILE_METADATA_PARAM_DEF_ID","DATA_FILE_ID")
)
;

CREATE TABLE "WEATHER" (
	"WEATHER_ID" int NOT NULL ,
	"DESCRIPTION" varchar (30) CONSTRAINT "UNIQUE_WEATHER_DESCRIPTION" UNIQUE ,
	"TITLE" varchar (30) NOT NULL  CONSTRAINT "UNIQUE_WHEATER_TITLE" UNIQUE ,
	"ORA_ROWSCN" BIGINT,
PRIMARY KEY ("WEATHER_ID")
)
;

CREATE TABLE "HEARING_IMPAIRMENT" (
	"HEARING_IMPAIRMENT_ID" int NOT NULL ,
	"DESCRIPTION" varchar (30) NOT NULL  CONSTRAINT "UNIQUE_HARING_DEFECT_DESCRIPTI" UNIQUE ,
PRIMARY KEY ("HEARING_IMPAIRMENT_ID")
)
;

CREATE TABLE "VISUAL_IMPAIRMENT" (
	"VISUAL_IMPAIRMENT_ID" int NOT NULL ,
	"DESCRIPTION" varchar (30) NOT NULL  CONSTRAINT "UNIQUE_EYES_DEFECT_DESCRIPTION" UNIQUE ,
PRIMARY KEY ("VISUAL_IMPAIRMENT_ID")
)
;

CREATE TABLE "HEARING_IMPAIRMENT_REL" (
	"PERSON_ID" int NOT NULL ,
	"HEARING_IMPAIRMENT_ID" int NOT NULL ,
PRIMARY KEY ("PERSON_ID","HEARING_IMPAIRMENT_ID")
)
;

CREATE TABLE "VISUAL_IMPAIRMENT_REL"  (
	"VISUAL_IMPAIRMENT_ID" int NOT NULL ,
	"PERSON_ID" int NOT NULL ,
PRIMARY KEY ("VISUAL_IMPAIRMENT_ID","PERSON_ID")
)
;

CREATE TABLE "PERSON_OPT_PARAM_DEF" (
	"PERSON_OPT_PARAM_DEF_ID" int NOT NULL ,
	"PARAM_NAME" varchar (30) NOT NULL ,
	"PARAM_DATA_TYPE" varchar (20) NOT NULL ,
PRIMARY KEY ("PERSON_OPT_PARAM_DEF_ID")
)
;

CREATE TABLE "PERSON_OPT_PARAM_VAL" (
	"PARAM_VALUE" varchar (30) NOT NULL ,
	"PERSON_ID" int NOT NULL ,
	"PERSON_OPT_PARAM_DEF_ID" int NOT NULL ,
PRIMARY KEY ("PERSON_ID","PERSON_OPT_PARAM_DEF_ID")
)
;

CREATE TABLE "EXPERIMENT_OPT_PARAM_DEF" (
	"EXPERIMENT_OPT_PARAM_DEF_ID" int NOT NULL ,
	"PARAM_NAME" varchar (30) NOT NULL ,
	"PARAM_DATA_TYPE" varchar (20) NOT NULL ,
PRIMARY KEY ("EXPERIMENT_OPT_PARAM_DEF_ID")
)
;

CREATE TABLE "EXPERIMENT_OPT_PARAM_VAL" (
	"PARAM_VALUE" varchar (30) NOT NULL ,
	"EXPERIMENT_ID" int NOT NULL ,
	"EXPERIMENT_OPT_PARAM_DEF_ID" int NOT NULL ,
PRIMARY KEY ("EXPERIMENT_ID","EXPERIMENT_OPT_PARAM_DEF_ID")
)
;

CREATE TABLE "FILE_METADATA_PARAM_DEF" (
	"PARAM_NAME" varchar (30) NOT NULL ,
	"FILE_METADATA_PARAM_DEF_ID" int NOT NULL ,
	"PARAM_DATA_TYPE" varchar (20) NOT NULL ,
PRIMARY KEY ("FILE_METADATA_PARAM_DEF_ID")
)
;

CREATE TABLE "RESEARCH_GROUP" (
	"RESEARCH_GROUP_ID" int NOT NULL ,
	"OWNER_ID" int NOT NULL ,
	"TITLE" varchar (100) NOT NULL ,
	"DESCRIPTION" varchar (250) NOT NULL ,
	"ORA_ROWSCN" BIGINT,
PRIMARY KEY ("RESEARCH_GROUP_ID")
)
;

CREATE TABLE "RESEARCH_GROUP_MEMBERSHIP" (
	"PERSON_ID" int NOT NULL ,
	"RESEARCH_GROUP_ID" int NOT NULL ,
	"AUTHORITY" varchar (30) NOT NULL ,
PRIMARY KEY ("PERSON_ID","RESEARCH_GROUP_ID")
)
;

CREATE TABLE "HISTORY" (
	"HISTORY_ID" int NOT NULL ,
	"EXPERIMENT_ID" int,
	"SCENARIO_ID" int,
	"PERSON_ID" int NOT NULL ,
	"DATA_FILE_ID" int,
	"DATE_OF_DOWNLOAD" DATE DEFAULT 'now' NOT NULL ,
PRIMARY KEY ("HISTORY_ID")
)
;

CREATE TABLE "ARTICLES" (
	"ARTICLE_ID" int NOT NULL ,
	"RESEARCH_GROUP_ID" int,
	"TEXT" clob NOT NULL ,
	"TIME" DATE DEFAULT 'now' NOT NULL ,
	"TITLE" varchar (150) NOT NULL ,
	"PERSON_ID" int NOT NULL ,
	"ORA_ROWSCN" BIGINT,
PRIMARY KEY ("ARTICLE_ID")
)
;

CREATE TABLE "ARTICLES_COMMENTS" (
	"COMMENT_ID" int NOT NULL ,
	"ARTICLE_ID" int NOT NULL ,
	"PARENT_ID" int NOT NULL ,
	"PERSON_ID" int NOT NULL ,
	"TEXT" clob NOT NULL ,
	"TIME" DATE DEFAULT 'now' NOT NULL ,
PRIMARY KEY ("COMMENT_ID")
)
;

CREATE TABLE "GROUP_PERMISSION_REQUEST" (
	"REQUEST_ID" int NOT NULL ,
	"REQUESTED_PERMISSION" varchar (20) NOT NULL ,
	"GRANTED" bigint NOT NULL ,
	"RESEARCH_GROUP_ID" int NOT NULL ,
	"PERSON_ID" int NOT NULL ,
PRIMARY KEY ("REQUEST_ID")
)
;

CREATE TABLE "ARTICLES_SUBSCRIBTIONS" (
	"ARTICLE_ID" int NOT NULL ,
	"PERSON_ID" int NOT NULL ,
PRIMARY KEY ("ARTICLE_ID","PERSON_ID")
)
;


CREATE TABLE "LAST_SYNC" (
  "TABLE_NAME" VARCHAR(40) NOT NULL,
  "VALUE" BIGINT not null
);

INSERT INTO LAST_SYNC ("TABLE_NAME" , "VALUE") VALUES('EXPERIMENT', 0);
INSERT INTO LAST_SYNC ("TABLE_NAME" , "VALUE") VALUES('DATA_FILE', 0);
INSERT INTO LAST_SYNC ("TABLE_NAME" , "VALUE") VALUES('SCENARIO', 0);
INSERT INTO LAST_SYNC ("TABLE_NAME" , "VALUE") VALUES('RESEARCH_GROUP', 0);
INSERT INTO LAST_SYNC ("TABLE_NAME" , "VALUE") VALUES('HARDWARE', 0);
INSERT INTO LAST_SYNC ("TABLE_NAME" , "VALUE") VALUES('WEATHER', 0);
INSERT INTO LAST_SYNC ("TABLE_NAME" , "VALUE") VALUES('PERSON', 0);