package ch.ethz.origo.jerpa.prezentation.perspective.signalprocess.info;

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 * Panel with informations about EEG record.
 * 
 * @author Jiri Kucera (original class from jERP Studio)
 * @author Vaclav Souhrada
 * @version 0.1.0 (11/17/09)
 * @since 0.1.0 (11/17/09)
 */
public class SignalInfoPanel extends JPanel {

	/** Only for serialization */
	private static final long serialVersionUID = -3776887971435045462L;
	
	private SignalInfoProvider infoProvider;
	private JTable channelsInfoTable;
	private JTable infoTable;
	private JScrollPane infoTableScrollPane;
	private JScrollPane jScrollPane1;

	/**
	 * Creates new form InfoWindow
	 * 
	 * @param infoWindowProvider
	 */
	public SignalInfoPanel(final SignalInfoProvider infoProvider) {
		this.infoProvider = infoProvider;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		infoTableScrollPane = new JScrollPane();
		infoTable = new JTable();
		jScrollPane1 = new JScrollPane();
		channelsInfoTable = new JTable();

		infoTable.setModel(infoProvider.getGlobalInfoDataModel());
		infoTable.setEnabled(false);
		infoTableScrollPane.setViewportView(infoTable);

		channelsInfoTable.setModel(infoProvider.getChannelsInfoDataModel());
		channelsInfoTable.setEnabled(false);
		jScrollPane1.setViewportView(channelsInfoTable);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap()
						.addGroup(
								layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING).addComponent(
										jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
										.addComponent(infoTableScrollPane,
												javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 457,
												Short.MAX_VALUE)).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(
						infoTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 158,
						javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
						jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465,
						Short.MAX_VALUE).addContainerGap()));
	}

	public void refresh() {
		infoTable.clearSelection();
		infoTable.revalidate();
		infoTable.repaint();
		channelsInfoTable.clearSelection();
		channelsInfoTable.revalidate();
		channelsInfoTable.repaint();
	}

	public void setItemsEnabled(boolean enabled) {
		infoTable.setEnabled(enabled);
		channelsInfoTable.setEnabled(enabled);
	}

}