/*
 *    This program is free software; you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation; either version 2 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program; if not, write to the Free Software
 *    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/*
 *  
 *    Copyright (C) 2009 - 2011 
 *    							University of West Bohemia, 
 *                  Department of Computer Science and Engineering, 
 *                  Pilsen, Czech Republic
 */
package ch.ethz.origo.jerpa.prezentation.perspective.signalprocess.importdialog;

import java.util.ResourceBundle;

import javax.swing.SwingUtilities;

/**
 * Panel for select target project for import averages
 * 
 * @author Jiri Kucera (jERP Studio)
 * @author Vaclav Souhrada (v.souhrada at gmail.com)
 * @version 1.0.0 (4/26/2011)
 * @since 0.1.0 (3/20/2010)
 */
public class TargetPanel extends javax.swing.JPanel {

	/** Only for serialization */
	private static final long serialVersionUID = -5460803600462974904L;

	/** Creates new form TargetPanel */
	public TargetPanel(ResourceBundle resource) {
		initComponents();
		targetProjectButtonGroup.add(importRadioButton);
		targetProjectButtonGroup.add(newProjectRadioButton);
		updateText(resource);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		targetProjectButtonGroup = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		importRadioButton = new javax.swing.JRadioButton();
		newProjectRadioButton = new javax.swing.JRadioButton();
		projectNameTextField = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();

		importRadioButton.setSelected(true);
		importRadioButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				importRadioButtonActionPerformed(evt);
			}
		});

		newProjectRadioButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						newProjectRadioButtonActionPerformed(evt);
					}
				});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												newProjectRadioButton)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												projectNameTextField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												117,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(jLabel1)
																						.addComponent(importRadioButton)))
														.addGroup(
																layout.createSequentialGroup().addGap(51, 51,
																		51).addComponent(jLabel2)))
										.addContainerGap(174, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addGap(18, 18, 18).addComponent(importRadioButton).addGap(18, 18,
								18).addComponent(newProjectRadioButton).addPreferredGap(
								javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
								layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE).addComponent(
										jLabel2).addComponent(projectNameTextField,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(
								164, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void importRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_importRadioButtonActionPerformed
		projectNameTextField.setEnabled(false);
	}// GEN-LAST:event_importRadioButtonActionPerformed

	private void newProjectRadioButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newProjectRadioButtonActionPerformed
		projectNameTextField.setEnabled(true);
	}// GEN-LAST:event_newProjectRadioButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	protected javax.swing.JRadioButton importRadioButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	protected javax.swing.JRadioButton newProjectRadioButton;
	protected javax.swing.JTextField projectNameTextField;
	private javax.swing.ButtonGroup targetProjectButtonGroup;
	// End of variables declaration//GEN-END:variables
	
	public void updateText(final ResourceBundle resource) {
		SwingUtilities.invokeLater(new Runnable() {
			
			@Override
			public void run() {
				jLabel1.setText(resource.getString("sp.diag.import.target.panel.target"));
				importRadioButton.setText(resource.getString("sp.diag.import.target.panel.imp.proj"));
				newProjectRadioButton.setText(resource.getString("sp.diag.import.target.panel.new.proj"));
				projectNameTextField.setText(resource.getString("sp.diag.import.target.panel.proj.name.def"));
				jLabel2.setText(resource.getString("sp.diag.import.target.panel.proj.name"));
			}
		});
	}

}
