package ch.ethz.origo.jerpa.prezentation.perspective.signalprocess.importdialog;

/**
 * Panel pro v�b�r c�lov�ho projektu pro import pr�m�r�.
 * 
 * 
 * @author Jiri Kucera (jERP Studio)
 * @author Vaclav Souhrada (v.souhrada at gmail.com)
 * @version 0.1.0 (3/20/2010)
 * @since 0.1.0 (3/20/2010)
 */
public class TargetPanel extends javax.swing.JPanel {

	/** Only for serialization */
	private static final long serialVersionUID = -5460803600462974904L;

	/** Creates new form TargetPanel */
	public TargetPanel() {
		initComponents();
		targetProjectButtonGroup.add(importRadioButton);
		targetProjectButtonGroup.add(newProjectRadioButton);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		targetProjectButtonGroup = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		importRadioButton = new javax.swing.JRadioButton();
		newProjectRadioButton = new javax.swing.JRadioButton();
		projectNameTextField = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();

		jLabel1.setText("Select target for importing averages:");

		importRadioButton.setSelected(true);
		importRadioButton.setText("Import into current project");
		importRadioButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				importRadioButtonActionPerformed(evt);
			}
		});

		newProjectRadioButton.setText("Create new project");
		newProjectRadioButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						newProjectRadioButtonActionPerformed(evt);
					}
				});

		projectNameTextField.setText("Project1");

		jLabel2.setText("Project name:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												newProjectRadioButton)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												projectNameTextField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												117,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(jLabel1)
																						.addComponent(importRadioButton)))
														.addGroup(
																layout.createSequentialGroup().addGap(51, 51,
																		51).addComponent(jLabel2)))
										.addContainerGap(174, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addGap(18, 18, 18).addComponent(importRadioButton).addGap(18, 18,
								18).addComponent(newProjectRadioButton).addPreferredGap(
								javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
								layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE).addComponent(
										jLabel2).addComponent(projectNameTextField,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(
								164, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void importRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_importRadioButtonActionPerformed
		projectNameTextField.setEnabled(false);
	}// GEN-LAST:event_importRadioButtonActionPerformed

	private void newProjectRadioButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newProjectRadioButtonActionPerformed
		projectNameTextField.setEnabled(true);
	}// GEN-LAST:event_newProjectRadioButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	protected javax.swing.JRadioButton importRadioButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	protected javax.swing.JRadioButton newProjectRadioButton;
	protected javax.swing.JTextField projectNameTextField;
	private javax.swing.ButtonGroup targetProjectButtonGroup;
	// End of variables declaration//GEN-END:variables

}
